postman/urls.py
"""
If the default usage of the views suits you, simply use a line like
this one in your root URLconf to set up the default URLs::

    path('messages/', include('postman.urls', namespace='postman')),

Otherwise you may customize the behavior by passing extra parameters.

Recipients Max
--------------
Views supporting the parameter are: ``WriteView``, ``ReplyView``.
Example::
    ...View.as_view(max=3), name='write'),
See also the ``POSTMAN_DISALLOW_MULTIRECIPIENTS`` setting

User filter
-----------
Views supporting a user filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_user_filter(user):
        if user.get_profile().is_absent:
            return "is away"
        return None
    ...
    ...View.as_view(user_filter=my_user_filter), name='write'),

function interface:
In: a User instance
Out: None, False, '', 'a reason', or ValidationError

Exchange filter
---------------
Views supporting an exchange filter are: ``WriteView``, ``ReplyView``.
Example::
    def my_exchange_filter(sender, recipient, recipients_list):
        if recipient.relationships.exists(sender, RelationshipStatus.objects.blocking()):
            return "has blacklisted you"
        return None
    ...
    ...View.as_view(exchange_filter=my_exchange_filter), name='write'),

function interface:
In:
    ``sender``: a User instance
    ``recipient``: a User instance
    ``recipients_list``: the full list of recipients or None
Out: None, False, '', 'a reason', or ValidationError

Auto-complete field
-------------------
Views supporting an auto-complete parameter are: ``WriteView``, ``ReplyView``.
Examples::
    ...View.as_view(autocomplete_channels=(None,'anonymous_ac')), name='write'),
    ...View.as_view(autocomplete_channels='write_ac'), name='write'),
    ...View.as_view(autocomplete_channel='reply_ac'), name='reply'),

Auto moderators
---------------
Views supporting an ``auto-moderators`` parameter are: ``WriteView``, ``ReplyView``.
Example::
    def mod1(message):
        # ...
        return None
    def mod2(message):
        # ...
        return None
    mod2.default_reason = 'mod2 default reason'
    ...
    ...View.as_view(auto_moderators=(mod1, mod2)), name='write'),
    ...View.as_view(auto_moderators=mod1), name='reply'),

function interface:
In: ``message``: a Message instance
Out: rating or (rating, "reason")
    with reting: None, 0 or False, 100 or True, 1..99

Others
------
Refer to documentation.
    ...View.as_view(form_classes=(MyCustomWriteForm, MyCustomAnonymousWriteForm)), name='write'),
    ...View.as_view(form_class=MyCustomFullReplyForm), name='reply'),
    ...View.as_view(form_class=MyCustomQuickReplyForm), name='view'),
    ...View.as_view(template_name='my_custom_view.html'), name='view'),
    ...View.as_view(success_url='postman:inbox'), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='reply'),
    ...View.as_view(formatters=(format_subject, format_body)), name='view'),

"""
from django import VERSION
from django.conf import settings
if VERSION < (2, 0):
    from django.conf.urls import url as re_path
else:
    from django.urls import re_path
if getattr(settings, 'POSTMAN_I18N_URLS', False):
    from django.utils.translation import pgettext_lazy
else:
    def pgettext_lazy(c, m): return m

from .views import (InboxView, SentView, ArchivesView, TrashView,
        WriteView, ReplyView, MessageView, ConversationView,
        ArchiveView, DeleteView, UndeleteView, MarkReadView, MarkUnreadView,
        IndexView)

app_name = 'postman'
urlpatterns = [
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    re_path(pgettext_lazy('postman_url', r'^inbox/(?:(?P<option>m)/)?$'), InboxView.as_view(), name='inbox'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    re_path(pgettext_lazy('postman_url', r'^sent/(?:(?P<option>m)/)?$'), SentView.as_view(), name='sent'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    re_path(pgettext_lazy('postman_url', r'^archives/(?:(?P<option>m)/)?$'), ArchivesView.as_view(), name='archives'),
    # Translators: keep consistency of the <option> parameter with the translation for 'm'
    re_path(pgettext_lazy('postman_url', r'^trash/(?:(?P<option>m)/)?$'), TrashView.as_view(), name='trash'),
    re_path(pgettext_lazy('postman_url', r'^write/(?:(?P<recipients>[^/#]+)/)?$'), WriteView.as_view(), name='write'),
    re_path(pgettext_lazy('postman_url', r'^reply/(?P<message_id>[\d]+)/$'), ReplyView.as_view(), name='reply'),
    re_path(pgettext_lazy('postman_url', r'^view/(?P<message_id>[\d]+)/$'), MessageView.as_view(), name='view'),
    # Translators: 't' stands for 'thread'
    re_path(pgettext_lazy('postman_url', r'^view/t/(?P<thread_id>[\d]+)/$'), ConversationView.as_view(), name='view_conversation'),
    re_path(pgettext_lazy('postman_url', r'^archive/$'), ArchiveView.as_view(), name='archive'),
    re_path(pgettext_lazy('postman_url', r'^delete/$'), DeleteView.as_view(), name='delete'),
    re_path(pgettext_lazy('postman_url', r'^undelete/$'), UndeleteView.as_view(), name='undelete'),
    re_path(pgettext_lazy('postman_url', r'^mark-read/$'), MarkReadView.as_view(), name='mark-read'),
    re_path(pgettext_lazy('postman_url', r'^mark-unread/$'), MarkUnreadView.as_view(), name='mark-unread'),
    re_path(r'^$', IndexView.as_view()),
]

postman/templates/postman/archives.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Archived Messages" %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder will never be removed. You can use this folder for long term storage." %}</p>
{% endblock %}

postman/templates/postman/base.html
{% extends "base.html" %}{# not myself but a site-level one (TEMPLATE_DIRS setting) #}
{% load i18n static %}{% load postman_tags %}
{% block title %}{% trans "Messaging" %}{% endblock %}
{% block extrahead %}{{ block.super }}
<link type="text/css" media="all" rel="stylesheet" href="{% static 'postman/css/postman.css' %}">
{% endblock %}
{% block postman_menu %}
<ul id="postman_menu">{% postman_unread as unread_count %}
 <li><a href="{% url 'postman:inbox' %}">&raquo;&nbsp;{% trans "Inbox" %}{% if unread_count %} <strong>({{ unread_count }})</strong>{% endif %}</a></li>
 <li><a href="{% url 'postman:sent' %}">&raquo;&nbsp;{% trans "Sent Messages" %}</a></li>
 <li><a href="{% url 'postman:write' %}">&raquo;&nbsp;{% trans "Write" %}</a></li>
 <li><a href="{% url 'postman:archives' %}">&raquo;&nbsp;{% trans "Archives" %}</a></li>
 <li><a href="{% url 'postman:trash' %}">&raquo;&nbsp;{% trans "Trash" %}</a></li>
</ul>
{% endblock %}

postman/templates/postman/base_folder.html
{% extends "postman/base.html" %}
{% load i18n postman_tags %}{% load pagination_tags %}{% comment %}
WARNING: 'pagination_tags' is a name from the dj-pagination application.
For convenience, the design of this template is done with the use of that application.
Django-postman will still be working, even if that application is not installed, by providing a mock
for the template tag library.
If the real implementation is to be used, just make sure that 'dj_pagination' is declared before 'postman'
in the INSTALLED_APPS setting.
{% endcomment %}
{% block content %}
<div id="postman">
<h1>{% block pm_folder_title %}{% endblock %}</h1>
{% autopaginate pm_messages %}
{% if invalid_page %}
<p>{% trans "Sorry, this page number is invalid." %}</p>
{% else %}
{% if pm_messages %}
{% block pm_by_modes %}<div id="pm_byModes">
<span class="pm_by-mode">{% if by_message %}<a href="{{ by_conversation_url }}">{% endif %}{% trans "by conversation" %}{% if by_message %}</a>{% endif %}</span>
<span class="pm_by-mode">{% if by_conversation %}<a href="{{ by_message_url }}">{% endif %}{% trans "by message" %}{% if by_conversation %}</a>{% endif %}</span>
</div>{% endblock pm_by_modes %}
<form action="{% block pm_form_action %}{% endblock %}" method="post">{% csrf_token %}
{% block pm_form_buttons %}<span id="pm_buttons">
{% block pm_delete_button %}<button type="submit" class="pm_btn pm_btn-delete" onclick="this.form.action='{% url 'postman:delete' %}'">{% trans "Delete" %}</button>{% endblock %}
{% block pm_archive_button %}<button type="submit" class="pm_btn pm_btn-archive" onclick="this.form.action='{% url 'postman:archive' %}'">{% trans "Archive" %}</button>{% endblock %}
{% block pm_undelete_button %}<button type="submit" class="pm_btn pm_btn-undelete" onclick="this.form.action='{% url 'postman:undelete' %}'">{% trans "Undelete" %}</button>{% endblock %}
{% block pm_read_button %}<button type="submit" class="pm_btn pm_btn-read" onclick="this.form.action='{% url 'postman:mark-read' %}'">{% trans "Mark as read" %}</button>{% endblock %}
{% block pm_unread_button %}<button type="submit" class="pm_btn pm_btn-unread" onclick="this.form.action='{% url 'postman:mark-unread' %}'">{% trans "Mark as unread" %}</button>{% endblock %}
</span>{% endblock %}
<table id="pm_messages">
 <thead>
  <tr>
   <th>{% trans "Action" %}</th>
{% block pm_sender_header %}   <th><a href="{% postman_order_by sender %}">{% trans "Sender" %}</a></th>{% endblock %}
{% block pm_recipient_header %}   <th><a href="{% postman_order_by recipient %}">{% trans "Recipient" %}</a></th>{% endblock %}
   <th><a href="{% postman_order_by subject %}">{% trans "Subject" %}</a></th>
   <th><a href="{% postman_order_by date %}">{% block pm_date %}{% trans "Date" %}{% endblock %}</a></th>
  </tr>
 </thead>
 <tbody>{% for message in pm_messages %}
  <tr>
   <td><input type="checkbox" {% if by_conversation and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %}></td>
{% block pm_sender_cell %}   <td>{{ message.obfuscated_sender|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %}
{% block pm_recipient_cell %}   <td>{{ message.obfuscated_recipient|or_me:user }}{% if message.count %} ({{ message.count }}){% endif %}</td>{% endblock %}
   <td>{% if message.is_new %}<strong>{% endif %}{% if message.is_replied %}<em>{% endif %}
{% block pm_subject %}
    <a href="{% if by_conversation and message.thread_id %}{% url 'postman:view_conversation' message.thread_id %}{% else %}{% url 'postman:view' message.pk %}{% endif %}?next={{ current_url|urlencode }}">
    {% include "postman/inc_subject_ex.html" %}
    </a>
{% endblock %}
   {% if message.is_replied %}</em>{% endif %}{% if message.is_new %}</strong>{% endif %}</td>
   <td>{{ message.sent_at|compact_date:_("g:i A,M j,n/j/y") }}</td>
  </tr>{% endfor %}
 </tbody>
</table>
</form>
{% paginate %}
{% else %}
<p>{% trans "No messages." %}</p>
{% endif %}
{% endif %}
{% block pm_footer_info %}{% endblock %}
</div>
{% endblock content %}

postman/templates/postman/base_write.html
{% extends "postman/base.html" %}
{% load i18n static %}
{% block extrahead %}{{ block.super }}
{% if autocompleter_app.is_active %}{# using the available admin jQuery is enough #}
{# should not be necessary since AS v1.3 with AJAX_SELECT_BOOTSTRAP set #}
{#<script type="text/javascript" src="{% static 'admin/js/jquery.min.js' %}"></script>#}
{% endif %}
{{ form.media }}{# for ajax_selects (v1.3.6 at least) #}
{% endblock %}
{% block content %}
<div id="postman">
<h1>{% block pm_write_title %}{% endblock %}</h1>
<form action="{% if next_url %}?next={{ next_url|urlencode }}{% endif %}" method="post">{% csrf_token %}
<table>
{% block pm_write_recipient %}{% endblock %}
{{ form.as_table }}
</table>
<button type="submit" class="pm_btn pm_btn-send">{% trans "Send" %}</button>
</form>
</div>
{% endblock %}

postman/templates/postman/inbox.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Received Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_recipient_header %}{% endblock %}
{% block pm_date %}{% trans "Received" %}{% endblock %}
{% block pm_recipient_cell %}{% endblock %}

postman/templates/postman/inc_subject_ex.html
{% comment %}
This file is intended to be included, such as in postman/base_folder.html:
    {% include "postman/inc_subject_ex.html" %}

It provides an extended subject, as a replacement to a simple {{ message.subject }} tag.
Enhancements are:
* limit the subject length to a few words
* if there is still room up to a maximum number of words, then add the very first words of the body,
  in a grey style.

Examples:
With a total of at most 12 words, and 5 words of subject.
With body: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod."

With subject: "a subject of great interest for you":
"a subject of great interest ... - Lorem ipsum dolor sit amet, consectetur ..."

With subject: "a great interest":
"a great interest - Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed ..."

{% endcomment %}{% load postman_tags %}{% with message.subject|truncatewords:5 as truncated_subject %}{{ truncated_subject }}
{% with truncated_subject|wordcount as subject_wc %}{% with 12|sub:subject_wc as wc %}{% if message.body and wc > 0 %} - <span style="color: grey">{{ message.body|truncatewords:wc }}</span>{% endif %}{% endwith %}{% endwith %}{% endwith %}

postman/templates/postman/reply.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Reply"%}{% endblock %}
{% block pm_write_recipient %}<tr><th><label>{% trans "Recipient" %}:</label></th><td>{{ recipient }}</td></tr>{% endblock %}

postman/templates/postman/sent.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Sent Messages" %}{% endblock %}
{% block pm_undelete_button %}{% endblock %}
{% block pm_read_button %}{% endblock %}
{% block pm_unread_button %}{% endblock %}
{% block pm_sender_header %}{% endblock %}
{% block pm_date %}{% trans "Sent" %}{% endblock %}
{% block pm_sender_cell %}{% endblock %}

postman/templates/postman/trash.html
{% extends "postman/base_folder.html" %}
{% load i18n %}
{% block pm_folder_title %}{% trans "Deleted Messages" %}{% endblock %}
{% block pm_delete_button %}{% endblock %}
{% block pm_archive_button %}{% endblock %}
{% block pm_subject %}{# no link #}
     {% include "postman/inc_subject_ex.html" %}
{% endblock %}
{% block pm_footer_info %}
<p>{% trans "Messages in this folder can be removed from time to time. For long term storage, use instead the archive folder." %}</p>
{% endblock %}

postman/templates/postman/view.html
{% extends "postman/base.html" %}
{% load i18n %}{% load postman_tags %}
{% block content %}
<div id="postman">
<h1>{% if pm_messages|length > 1 %}{% trans "Conversation" %}{% else %}{% trans "Message" %}{% endif %}</h1>
{% for message in pm_messages %}
<div class="pm_message{% if message.is_pending %} pm_pending{% endif %}{% if message.is_rejected %} pm_rejected{% endif %}{% if message.sender == user and message.sender_archived or message.recipient == user and message.recipient_archived %} pm_archived{% endif %}{% if message.sender == user and message.sender_deleted_at or message.recipient == user and message.recipient_deleted_at %} pm_deleted{% endif %}{% if message.recipient == user and not message.read_at %} pm_unread{% endif %}">
 <div class="pm_header">
  <span class="pm_sender">{{ message.obfuscated_sender|or_me:user }}</span> &raquo;
  <span class="pm_recipient">{{ message.obfuscated_recipient|or_me:user }}</span> |
  <span class="pm_date">{{ message.sent_at|date:"DATETIME_FORMAT"}}</span> |
  <span class="pm_subject">{{ message.subject }}</span>
{% if message.is_rejected %}  <div class="pm_status">{% trans "Rejected" %}{% if message.moderation_reason %}{% trans ":" %} {{ message.moderation_reason }}{% endif %}</div>{% endif %}
 </div>
 <div class="pm_body">{{ message.body|linebreaksbr }}</div>
</div>
{% if forloop.last %}
<form action="" method="post">{% csrf_token %}
<input type="hidden" {% if pm_messages|length > 1 and message.thread_id %}name="tpks" value="{{ message.thread_id }}"{% else %}name="pks" value="{{ message.pk }}"{% endif %}>
<a href="{{ next_url }}" class="pm_action pm_action-back">{% trans "Back" %}</a>
<span id="pm_buttons">
<button type="submit" class="pm_btn pm_btn-delete"
 onclick="this.form.action='{% url 'postman:delete' %}?next={{ next_url|urlencode }}'">{% trans "Delete" %}</button>
{% if not archived %}<button type="submit" class="pm_btn pm_btn-archive"
 onclick="this.form.action='{% url 'postman:archive' %}?next={{ next_url|urlencode }}'">{% trans "Archive" %}</button>{% endif %}
</span>
{% if reply_to_pk %}<a href="{% url 'postman:reply' reply_to_pk %}?next={{ next_url|urlencode }}"
 class="pm_action pm_action-reply">{% trans "Reply" %}</a>{% endif %}
</form>
{% if reply_to_pk %}<hr />
<h2>{% trans 'Reply' %}</h2>
<form action="{% url 'postman:reply' reply_to_pk %}?next={{ next_url|urlencode }}" method="post">{% csrf_token %}
<div id="pm_reply">{{ form.body }}</div>
<button type="submit" class="pm_btn pm_btn-reply">{% trans 'Reply' %}</button>
</form>{% endif %}
{% endif %}
{% endfor %}
</div>
{% endblock %}

postman/templates/postman/write.html
{% extends "postman/base_write.html" %}
{% load i18n %}
{% block pm_write_title %}{% trans "Write"%}{% endblock %}